### ISSUE TITLE
Change neoclient Dependency to neo4j-php-client

### ISSUE THREAD

**Issue by gatewayiQ-LeadDev** [graphaware/php-graphunit#2]
graphaware/php-graphunit is currently dependant on  neoxygen/neoclient which in turn is dependant on an older version of symfony/event-dispatcher:

```
graphaware/neo4j-graphunit 1.0.0 requires neoxygen/neoclient ^3.1
neoxygen/neoclient 3.3.9 requires symfony/event-dispatcher ^2.7
```

I am currently running symfony/event-dispatcher 3.1.1. It would be great if graphaware/php-graphunit was instead dependant on graphaware/neo4j-php-client (neoxygen/neoclient successor).

**Comment by ikwattro** [comment]
Hi,

Are you using graphunit right now ? I'm happy to make those changes, just you are the first person I'm aware using this library.

Cheers

Chris

**Comment by gatewayiQ-LeadDev** [comment]
No, I am not currently using php-graphunit however I am loving neo4j-php-client and I need some way to use PHPUnit or something similar.

I had hoped to use Codeception however I am apparently the only person on the English speaking Internet who is interested in using it with Neo4j so now I am trying to settle for PHPUnit alone.

Regrettably I am only now finally learning and implementing proper testing and I really am a bit discouraged by and surprissed that everything seems to assume an RDBMS.

I have been using RDBMS's for years and only recently dived into graphs with Neo4j. I cannot figure out why graphs are not the standard for Web applications! Of course there are some things RDBMS's are better at, for example, I am storing customer invoices in PostgreSQL, but for all my user accounts, user content, roles/permissions system, etc. I am using Neo4j.

**Comment by ikwattro** [comment]
There will be a time before neo4j will be considered in the standard packages I'm afraid.

Based on my neo4j testing experience in the recent projects, I came up by building traits for integration/unit assertions.

I'm happy to extract these traits and open source then in the near future.

I don't think however I will upgrade that much the current version of graphunit, it is still more here for historical reasons as it is used in an old package.

There is also a data fixtures library from a friend of mine, available here : https://github.com/PandawanTechnology/neo4j-data-fixtures that can interest you.

Let me know what you think.

**Comment by gatewayiQ-LeadDev** [comment]
Thank you for your response. It feels a bit like I discovered graph databases a bit too early (as a Web developer that is--graph DBs are by no means new).

Thank you for the link--I will check that out. I also look forward to seeing improved support for testing with Neo4j--perhaps that will include your traits.
